FeatureProbe/FeatureProbe

- api/admin/src/main/java/com/featureprobe/api/builder/ServerToggleBuilder.java
- api/admin/src/main/java/com/featureprobe/api/config/AppConfig.java
- api/admin/src/main/java/com/featureprobe/api/controller/MetricController.java
- api/admin/src/main/java/com/featureprobe/api/dto/AnalysisResultResponse.java
- api/admin/src/main/java/com/featureprobe/api/service/BaseServerService.java
- api/admin/src/main/java/com/featureprobe/api/service/MetricService.java
- api/admin/src/main/java/com/featureprobe/api/service/TargetingService.java
- api/admin/src/main/resources/config/application-online.yml
- api/admin/src/test/groovy/com/featureprobe/api/service/BaseServerServiceSpec.groovy
- api/admin/src/test/groovy/com/featureprobe/api/service/CacheServerDataSourceSpec.groovy
- api/admin/src/test/groovy/com/featureprobe/api/service/MetricServiceSpec.groovy
- api/admin/src/test/groovy/com/featureprobe/api/service/ToggleServiceSpec.groovy
- api/base/pom.xml
- api/base/src/main/java/com/featureprobe/api/base/enums/ResourceType.java
- api/base/src/main/java/com/featureprobe/api/base/enums/TrafficType.java
- api/base/src/main/java/com/featureprobe/api/base/model/JSEvent.java
- api/dao/src/main/java/com/featureprobe/api/dao/entity/ServerToggleEntity.java
- api/dao/src/main/java/com/featureprobe/api/dao/entity/ToggleControlConf.java
- api/dao/src/main/java/com/featureprobe/api/dao/repository/EnvironmentRepository.java
- api/dao/src/main/java/com/featureprobe/api/dao/repository/ToggleControlConfRepository.java
- api/pom.xml
Fix # .
Changes proposed in this pull request: 
* add event analysis api
*
*
> Add event analysis api

- server/Cargo.lock
- server/Cargo.toml
- server/examples/local_file.rs
- server/resources/fixtures/repo.json
- server/src/base.rs
- server/src/http/handler.rs
- server/src/http/mod.rs
- server/src/main.rs
- server/src/repo.rs
Fix # .
* Support event analysis on server
*
*
> Support event analysis on server

- docs/docs/how-to/Client-Side SDKs/javascript-sdk.md
- docs/docs/how-to/Client-Side SDKs/react-sdk.md
- docs/i18n/zh-CN/docusaurus-plugin-content-docs/current/how-to/Client-Side SDKs/javascript-sdk.md
- docs/i18n/zh-CN/docusaurus-plugin-content-docs/current/how-to/Client-Side SDKs/react-sdk.md
Fix #177 
* Add how to use event tracking in React SDK
> docs: Update React SDK documentation

- ui/src/interfaces/analysis.ts
- ui/src/locales/en-US.json
- ui/src/locales/zh-CN.json
- ui/src/pages/analysis/components/Metrics/index.module.scss
- ui/src/pages/analysis/components/Metrics/index.tsx
- ui/src/pages/analysis/components/Results/components/table/index.tsx
- ui/src/pages/analysis/components/Results/index.tsx
- ui/src/utils/checkUrl.ts
Fix #162 .
* Check if current URL matches target URL
> ✨feat: add URL matching check when creating or editing an event

- api/admin/src/main/java/com/featureprobe/api/controller/MetricController.java
- api/admin/src/main/java/com/featureprobe/api/dto/MetricIterationResponse.java
- api/admin/src/main/java/com/featureprobe/api/mapper/MetricIterationMapper.java
- api/admin/src/main/java/com/featureprobe/api/mapper/TargetingVersionMapper.java
- api/admin/src/main/java/com/featureprobe/api/service/MetricService.java
- api/admin/src/main/java/com/featureprobe/api/service/TargetingService.java
- api/admin/src/main/java/com/featureprobe/api/service/ToggleControlConfService.java
- api/admin/src/main/resources/db/migration/V50__add_metric_iteration_table.sql
- api/admin/src/main/resources/i18n/messages_en_US.properties
- api/admin/src/main/resources/i18n/messages_zh_CN.properties
- api/admin/src/test/groovy/com/featureprobe/api/service/MetricServiceSpec.groovy
- api/admin/src/test/groovy/com/featureprobe/api/service/SegmentServiceSpec.groovy
- api/admin/src/test/groovy/com/featureprobe/api/service/ToggleControlConfServiceSpec.groovy
- api/dao/src/main/java/com/featureprobe/api/dao/entity/MetricIteration.java
- api/dao/src/main/java/com/featureprobe/api/dao/repository/MetricIterationRepository.java
- api/dao/src/main/java/com/featureprobe/api/dao/repository/TargetingVersionRepository.java
…etric analysis
Fix #161 
* add the "Collection Process" and "Data Observation Window" to metric analysis
*
*
> ✨feat: add the "Collection Process" and "Data Observation Window" to metric analysis

- api/admin/src/main/java/com/featureprobe/api/dto/ToggleSegmentResponse.java
- api/admin/src/main/java/com/featureprobe/api/service/SegmentService.java
- api/admin/src/test/groovy/com/featureprobe/api/service/SegmentServiceSpec.groovy
…ment toggle list
Fix # . #158 
* 
*Add status field for metric analysis in the user segment toggle list
*
> :sparkles: feat: Add status field for metric analysis in the user segment toggle list

- docs/docs/reference/sdk-contributor.md
- docs/i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/sdk-contributor.md
Fix # . #199 
*  add sdk contribution guide docs
*
*
> :book: docs: add sdk contribution guide

- ui/src/pages/connectSDK/components/TestConnection/index.tsx
> ✨feat: add metric troubleshoot FAQ

- docs/docs/how-to/Server-Side SDKs/node-sdk.md
- docs/i18n/zh-CN/docusaurus-plugin-content-docs/current/how-to/Server-Side SDKs/java-sdk.md
- docs/i18n/zh-CN/docusaurus-plugin-content-docs/current/how-to/Server-Side SDKs/node-sdk.md
- ui/src/pages/connectSDK/components/TrackEvent/index.tsx
- ui/src/pages/connectSDK/constants.ts
Fix: #107
* Update Node.js documentation
* Update user guide of event track  when connecting Node.js SDK
> feat: add event track of Node.js SDK

- docs/docs/how-to/Server-Side SDKs/python-sdk.md
- docs/i18n/zh-CN/docusaurus-plugin-content-docs/current/how-to/Server-Side SDKs/python-sdk.md
- ui/src/locales/en-US.json
- ui/src/locales/zh-CN.json
- ui/src/pages/analysis/components/Metrics/index.tsx
- ui/src/pages/connectSDK/components/TrackEvent/index.tsx
- ui/src/pages/connectSDK/constants.ts
- ui/src/pages/connectSDK/index.tsx
> :books:docs: Add `track` api to python

- analysis/src/main/kotlin/com/featureprobe/api/analysis/AnalysisFunction.kt
- analysis/src/test/kotlin/com/featureprobe/api/analysis/AnalysisFunctionTests.kt
* refactor function winningPercentage 
* add more UT
> Refactor sampling

- api/admin/src/main/java/com/featureprobe/api/service/MetricService.java
- api/base/src/main/java/com/featureprobe/api/base/enums/MetricTypeEnum.java
Fix #227 
* Support for metrics such as average, sum, and count.
*
*
> ✨ feat: Support for metrics such as average, sum, and count.

- analysis/src/main/kotlin/com/featureprobe/api/analysis/AnalysisController.kt
- analysis/src/main/kotlin/com/featureprobe/api/analysis/AnalysisFunction.kt
- analysis/src/main/kotlin/com/featureprobe/api/analysis/AnalysisModel.kt
- analysis/src/test/kotlin/com/featureprobe/api/analysis/AnalysisControllerTests.kt
- analysis/src/test/resources/init.sql
- docs/docs/introduction/faq.md
- docs/i18n/zh-CN/docusaurus-plugin-content-docs/current/introduction/faq.md
> feat: diagnose analysis

- api/admin/src/main/java/com/featureprobe/api/controller/MetricController.java
- api/admin/src/main/java/com/featureprobe/api/service/MetricService.java
Fix #237 
* ✨ feat: support metric analysis diagnosis
*
*
> ✨ feat: support metric analysis diagnosis

- api/admin/src/main/java/com/featureprobe/api/service/TargetingService.java
> :bug: fix: refresh issue with creation of toggle buffer

- docs/docs/how-to/Client-Side SDKs/react-sdk.md
- docs/i18n/zh-CN/docusaurus-plugin-content-docs/current/how-to/Client-Side SDKs/react-sdk.md
- ui/src/pages/connectSDK/constants.ts
> :bug:bug: npm package address error

- server/Cargo.lock
- server/Cargo.toml
- server/src/repo.rs
Fix #253
*  support debug event for server
*
*
> :sparkles: feat: support debug event for server

- analysis/src/main/kotlin/com/featureprobe/api/analysis/AnalysisController.kt
- analysis/src/main/kotlin/com/featureprobe/api/analysis/AnalysisFunction.kt
- analysis/src/main/kotlin/com/featureprobe/api/analysis/AnalysisModel.kt
- analysis/src/main/resources/db/migration/V4__alter_kind_field.sql
- analysis/src/test/kotlin/com/featureprobe/api/analysis/AnalysisControllerTests.kt
Fix #253
* support event tracker feature
*
*
> :sparkles: feat: support event tracker for analysis

- ui/src/pages/traffic/chartOption.ts
- ui/src/pages/traffic/index.tsx
> :hammer:fix: replace _active with getActiveElements

- api/admin/pom.xml
- api/admin/src/main/java/io/featureprobe/api/auth/LdapAccountValidator.java
- api/admin/src/main/java/io/featureprobe/api/config/LdapConfig.java
- api/admin/src/test/groovy/io/featureprobe/api/service/UserPasswordAuthenticationProviderSpec.groovy
support ldap authenticate,
- #293
> feat: support ldap authenticate

- docs/docs/reference/identity-authenticate.md
- docs/i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/identity-authenticate.md
> docs: ldap support

- ui/src/pages/connectSDK/constants.ts
> fix: gosdk version display upgrade,v2

- api/admin/src/main/java/io/featureprobe/api/auth/LdapAccountValidator.java
- api/admin/src/main/java/io/featureprobe/api/config/LdapConfig.java
- api/admin/src/test/groovy/io/featureprobe/api/service/UserPasswordAuthenticationProviderSpec.groovy
- docs/docs/reference/identity-authenticate.md
- ui/yarn.lock
* Add support for configuring LDAP user name attribute
> Add configuration support for LDAP user name attribute

- server/Dockerfile
> feat: Update rust to 1.65.0 for server Dockerfile

- server/Dockerfile
> feat: Update rust to 1.67.0 for server Dockerfile

- docs/docs/how-to/Server-Side SDKs/python-sdk.md
- docs/docs/introduction/faq.md
- docs/docs/tutorials/analysis.md
- docs/docs/tutorials/backend_custom_attribute.md
- docs/docs/tutorials/rollout_tutorial/index.md
- docs/docs/tutorials/rollout_tutorial/stable_rollout_tutorial.md
- docs/docs/tutorials/user_segment_tutorial.md
- docs/i18n/zh-CN/docusaurus-plugin-content-docs/current/how-to/Server-Side SDKs/python-sdk.md
- docs/i18n/zh-CN/docusaurus-plugin-content-docs/current/introduction/faq.md
- docs/i18n/zh-CN/docusaurus-plugin-content-docs/current/tutorials/analysis.md
- docs/i18n/zh-CN/docusaurus-plugin-content-docs/current/tutorials/backend_custom_attribute.md
- docs/i18n/zh-CN/docusaurus-plugin-content-docs/current/tutorials/rollout_tutorial/index.md
- docs/i18n/zh-CN/docusaurus-plugin-content-docs/current/tutorials/rollout_tutorial/stable_rollout_tutorial.md
- docs/i18n/zh-CN/docusaurus-plugin-content-docs/current/tutorials/user_segment_tutorial.md
- ui/src/pages/connectSDK/constants.ts
Fix # .
* SyncMode填写错误，更正为polling
> fix: SyncMode填写错误，更正为polling

- api/admin/src/main/java/io/featureprobe/api/service/MemberService.java
version: 2.7.0
Fix # . when a member deleted, page load error. API NPE. https://github.com/FeatureProbe/FeatureProbe/issues/378
* change stream() in method "io.featureprobe.api.service.MemberService#convertToResponse"
> bugfix: when delete a member, page load error.
